### ISSUE TITLE
Implement logon/logoff

### ISSUE THREAD

**Issue by hypnotichen** [DIBL/mini_wechat#15]
Similar to registration, let's implement logon and logoff before entering database.

- For the most part, logon and logoff just toggle a flag indicating whether or not a user is currently active, which causes different handling of chat messages (which we don't need to worry at the moment). This flag should be stored in memory for now.

- For both logon and logoff, we need to handle repeated requests, e.g. the same user send logon/logoff requests multiple times. In either case we can choose to either return an error or silently ignore the duplicated requests.

- We will need to define protos for logon and off. 

- Client needs 2 new methods, one for logon and one for logoff. Similarly, server needs 2 more handlers, one for each request.

**Comment by DIBL** [comment]
> For both logon and logoff, we need to handle repeated requests
Does this issue only exists in our case? If there is UI for client, there shouldn't be repeated request for login/log off, correct?

**Comment by hypnotichen** [comment]
Yes, you are correct.
