### ISSUE TITLE
Database support (for registration/logon/logoff)

### ISSUE THREAD

**Issue by hypnotichen** [DIBL/mini_wechat#16]
So far we have been storing user information in memory, which is fast to access but the data will be lost if server crashes/shuts down/restarts. And we need a storage layer to persist all such important information.

Since nosql services are relatively easy to setup and use, let's start with them (this doesn't mean nosql is better than relational database! And in fact we will implement a relational storage layer later as comparison). There are a bunch of free nosql products for us to choose from, so let's do some reading before picking one. Below are some high level introduction to nosql:
https://www.thoughtworks.com/insights/blog/nosql-no-problem-intro-nosql-databases
https://www.cognitiveclouds.com/insights/should-you-use-a-nosql-db-sql-database-or-both/
https://medium.com/xplenty-blog/the-sql-vs-nosql-difference-mysql-vs-mongodb-32c9980e67b2
https://shuaiw.github.io/2017/08/18/choosing-a-nosql-db.html
https://bigdata-madesimple.com/18-free-and-widely-used-open-source-nosql-databases/

For this task:
- Do the readings above and once we pick 2 or 3 candidates, read a bit from their official documents as well
- Pick a nosql database, install the server locally, and add necessary client libraries to our project
- Determine what need to be stored for registration/logon/logoff and setup the table/collection if necessary
- At server side, replace in memory map by using the nosql database for registration/logon/logoff.

Notes:
- Try to find a good "schema" for storing user information (so it's efficient to query/update the database) but don't worry too much about performance yet, let's make everything working first
- Because we want to support a relational storage eventually, you should design a set of common interfaces for the storage layer and provide different implementations for nosql and relational db, which allow us to switch implementation with only a config change.

**Comment by DIBL** [comment]
Can we close this issue?
