### ISSUE TITLE
Adding metrics

### ISSUE THREAD

**Issue by hypnotichen** [DIBL/mini_wechat#17]
It's almost always important to know how fast our service can serve the requests and to do that we need to record metrics.

For our purpose, maybe below 2 types of metrics are useful:
1) how many times something happens. This tells us which part of the code is on the hot path thus we know where we should focus on
2) how long does it take our service to perform some task. for example, how many milliseconds to read/write database and so on. Common timing metrics are average/median/90%.

For this task:
- Write 1 or 2 classes that supports above metrics.
- Record how many times each database operation are performed and how long does it take on average.
- Print the metrics periodically.

**Comment by DIBL** [comment]
Can we close on this?
