### ISSUE TITLE
Write a program for performance test

### ISSUE THREAD

**Issue by hypnotichen** [DIBL/mini_wechat#27]
We should finish both #23 and #17 before starting on this.

To see the performance impact of cache, syn/async and push/pull, we would need a small program to send requests from client to server (so we get enough data points to compare metrics).

Requirements of the program:
- Send messages between 2 existing users
- Usernames of the 2 users should be configurable
- How many messages to send between the 2 users should be configurable
- There should be some fake interactions between the 2 users. For example, A sends 3 messages to B and B responds with 2 messages. Then A sends 1 message to B and B responds with 2 messages and so on.
- We probably need a small shell script to be able to launch multiple instances of this programs at once (to simulate concurrent requests from multiple users)

**Comment by DIBL** [comment]
Can we close this issue?
