### ISSUE TITLE
implement pull mode

### ISSUE THREAD

**Issue by hypnotichen** [DIBL/mini_wechat#48]
Once kafka is setup and we figure out how to configure topics/partitions, we can start to implement pull mode.

On the server side:
- Probably need to make KafkaSender use KafkaProducer's send() function that takes a callback parameter for better performance.

On the client side:
- Need to implement a kafka puller which stays in a loop and keep pulling messages from kafka.
- And after a message is fetched, client should update database to update the messages' "delivered" flag.

**Comment by DIBL** [comment]
Can we do in this way?
- Update messages' isDeliver flag once successully push messages into kafka => We can continuously keep track of "undelivered" messages based on isDeliver flag and try adding them into Kafka maybe at fixed interval
- Setup client consumer as at-least-once => users should receive all messages at least once stored in Kafka

![image](https://user-images.githubusercontent.com/4529231/54726542-d96fb180-4b30-11e9-8e57-577ce872e2e0.png)

**Comment by hypnotichen** [comment]
Yeah, this is simple enough while at the same time seems to work in most of the scenarios.

A few things to note though:

- When starting the kafka server, we should configure it to keep the messages for a reasonable time. Otherwise if the user stays offline for a long time the messages will be deleted by kafka and never delivered to the user. In reality though we probably won't want to keep the messages at kafka for too long: if you have a lot of active users then we are going to explode kafka.

- The server side should not send message to kafka if the to_user is offline thus the status for those messages remain "undelivered" and they will be delivered when the next time user gets online.

- We should consider adding a heartbeat mechanism between server and all the clients. This way server will quickly know if a client is crashing and can log that client off and stop sending messages to kafka.

**Comment by DIBL** [comment]
> When starting the kafka server, we should configure it to keep the messages for a reasonable time. 
By default, it is set to 7 days in server.properties`log.retention.hours=168`
