### ISSUE TITLE
spring integration

### ISSUE THREAD

**Issue by hypnotichen** [DIBL/mini_wechat#49]
Now that we implemented both pull and push, it's probably good time to integrate Spring into the project, which would make switching between pull and push easier.

Let's use Spring Java config to manage the "beans".

**Comment by DIBL** [comment]
Is this the one we are looking for?
https://spring.io/guides/gs/spring-boot/

**Comment by hypnotichen** [comment]
Let's start with configuration:
https://docs.spring.io/spring/docs/3.0.0.M4/reference/html/ch03s11.html
